@startuml Architecture 2
[SignUpController] <-- [ValidatorAdapter]
[ValidatorAdapter] --> [Validator]

[SignUpController] <-- [ExpressAdapter]
[ExpressAdapter] --> [Express]

[SignUpController] <-- [MongoDBAdapter]
[MongoDBAdapter] --> [MongoDB]

[SignUpController] <-- [BCryptAdapter]
[BCryptAdapter] --> [BCrypt]
@enduml